### ISSUE TITLE
Beyond PSCC Paper: Branching between formulations with and without auxiliary variables based in "aux"

### ISSUE THREAD

**Issue by frederikgeth** [timmyfaraday/StochasticPowerModels.jl#23]
We have to think about where to branch on the 'aux' keyword in the code
- make separate formulations
- branch in problem specification
- branch in variable template (current choice)

**Comment by timmyfaraday** [comment]
In my opinion, the PSCC paper shows that any formulation with auxiliary variables is always superior. Consequently, upon acceptance, I would remove the formulations without auxiliary variables from the package in a future version. To this end, _in my opinion_, refactoring the code for this branching seems unnecessary in the long run.
