### ISSUE TITLE
Academic papers

### ISSUE THREAD

**Issue by wangxk9999** [timmyfaraday/StochasticPowerModels.jl#33]
Hello, timmyfaraday, this is a great job.
Can you show some academic papers about stochastic optimal power flow, i.e. StochasticPowerModels.jl.
Thank you very much.

**Comment by timmyfaraday** [comment]
The paper describing the work is submitted to PSCC2022 Porto, and currently under review. Therefore, it is not yet available. If the other authors are okay with it, I'm willing to share the submitted draft with you. Just send an email to: tom.vanacker@esat.kuleuven.be
