### ISSUE TITLE
PSCC paper: Convergence of the IEEE30-case

### ISSUE THREAD

**Issue by timmyfaraday** [timmyfaraday/StochasticPowerModels.jl#6]
Currently, the IEEE30-case does not converge.

**Comment by timmyfaraday** [comment]
Assumption and changes compared to base IEEE30:
- shunt elements are neglected
- voltage magnitude at slack bus 1 is assumed constant at one
- line current limits are set to the nominal values of the per-unit line ratings, except for two lines where the capacity is reduced from 16 to, 15-23: imax = 11, and 25-27: imax = 12.
- a stochastic germ ω comprised of four distinct sources of uncertainty, two Beta distributions (one symmetric, one non-symmetric) and two normal distributions as described in Table VI. [1]

[1] Chance-constrained AC optimal power flow - a polynomial chaos approach by Muhlpfordt et al.

**Comment by frederikgeth** [comment]
- PG lib case may not be the same as the one used by Muhlpfordt, as our case does not solve deterministically when setting branch shunts to 0
- PG lib case doesn't solve in the stochastic context

**Comment by timmyfaraday** [comment]
The Muhlpfordt implementation limits all expected voltages (k=1) between the following bounds: 
- 0.7 <= U_re <= 1.3
- -0.3 <= U_im <= 0.3

This might tighten the problem and be the reason for the larger objective value.

**Comment by timmyfaraday** [comment]
After obtaining the input file from Tillmann Muhlpfordt, an objective value of 599.35 is obtained, validating the IVR implementation against their ACR implementation.
